#!/usr/bin/env bash
# Get the PID of the "4-to_infinity_and_beyond" process
pid=$(pgrep -f "4-to_infinity_and_beyond")
if [ -n "$pid" ]; then
    kill -INT "$pid"
    echo ""
else
    echo "Process is not running"
fi
