#!/usr/bin/env bash
#prints best school 10 times
counter=0
while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
